name: Leavidence
version: '${project.version}'
main: io.wdsj.leavidence.Leavidence
api-version: '1.21'
author: HaHaWTH
description: Prevent Leaves bots break blocks in the residence without permission.
depend:
  - Residence